### ISSUE TITLE
Cómo jugador, quiero ver líneas representando cada letra del país a adivinar

### ISSUE THREAD

**Issue by sagodi97** [magodi9/U.S.S.R#1]
**QUE:** Cuando el juego empieza, el jugador debería ver líneas en vez de letras para empezar a adivinar el pais. Por ejemplo, en vez de Rusia, mostrar __ __ __ __ __ .
**PORQUE:** Por que este juego es basado en el clásico "ahorcado".

**Comment by magodi9** [comment]
La solución se encuentra en el últimos commit "desaparecer menú y aparecer guion por cada letra"

**Comment by sagodi97** [comment]
Solved by @magodi9 in commit https://github.com/magodi9/U.S.S.R/commit/0f4649dab3121b62241f97b592ede51c6130d607 👏🏼
